// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Services.ProductAPI.DbContexts;

#nullable disable

namespace Shop.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240103203915_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Мужской парфюм",
                            ProductDescription = "Магнетический аромат со свежими нотами",
                            ProductImg = "https://vodar.by/media/catalog/product/cache/1/small_image/165x/9df78eab33525d08d6e5fb8d27136e95/1/3/1349097256_1_.jpg",
                            ProductName = "Lacoste Eau De Lacoste L.12.12. Blanc",
                            ProductPrice = 760.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Женский парфюм",
                            ProductDescription = "Изысканный женский аромат с нотами цветов и цитрусовых",
                            ProductImg = "https://vodar.by/media/catalog/product/cache/1/small_image/165x/9df78eab33525d08d6e5fb8d27136e95/1/4/147565_1_.jpg",
                            ProductName = "Chanel Coco Mademoiselle",
                            ProductPrice = 900.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Женский парфюм",
                            ProductDescription = "Свежий и яркий аромат для женщин",
                            ProductImg = "https://vodar.by/media/catalog/product/cache/1/small_image/165x/9df78eab33525d08d6e5fb8d27136e95/d/o/dolce___gabbana_dolce_peony-_1_1__1_.jpg",
                            ProductName = "Dolce&Gabbana Dolce Peonye",
                            ProductPrice = 950.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
